### ISSUE TITLE
ONNX assembly jar not installable on Databricks Spark 3.3 clusters [BUG]

### ISSUE THREAD

**Issue by aero-girl** [microsoft/SynapseML#1817] opened 2023-02-01 11:26 UTC
### SynapseML version

com.microsoft.azure:synapseml_2.12:0.10.2

### System information

- **Language version** (e.g. python 3.8, scala 2.12): Python 3.9
- **Spark Version** (e.g. 3.2.3): Apache Spark 3.3.0
- **Spark Platform** (e.g. Synapse, Databricks): Databricks Runtime 11.3 LTS for Machine Learning 
 

### Describe the problem

Trying to install cognitive services on Databricks following this [instructions](https://microsoft.github.io/SynapseML/docs/getting_started/installation/#databricks) provided.

Have tried the following Maven coordinates: 
- com.microsoft.azure:synapseml_2.12:0.10.2
- com.microsoft.azure:synapseml_2.12:0.10.1 
- com.microsoft.azure:synapseml_2.12:0.10.0

They are fail and the following is the error message received:
"Library installation attempted on the driver node of cluster 0110-113436-jrinjmhu and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: java.util.concurrent.ExecutionException: java.io.FileNotFoundException: File file:/local_disk0/tmp/clusterWideResolutionDir/maven/ivy/jars/com.microsoft.azure_onnx-protobuf_2.12-0.9.1.jar does not exist"

I did have this working on the 14/01/2023 using the com.microsoft.azure:synapseml_2.12:0.10.2 Maven coordinates - see screenshot below. 

Thanks!

![image](https://user-images.githubusercontent.com/5180795/216029400-ebc93834-b8f9-480a-b6e0-c894a3de4df6.png)

### Code to reproduce issue

import pyspark
spark = pyspark.sql.SparkSession.builder.appName("MyApp")
        .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.10.2") # Please use 0.10.2 version for Spark3.2 and 0.9.5-13-d1b51517-SNAPSHOT version for Spark3.1
        .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven")
        .getOrCreate()

### What component(s) does this bug affect?

- [X] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by nakany15** [comment] 2023-02-01 14:26
I have encountered the same issue when using Databricks Runtime 11.3, but successfully installed when I downgraded to the Databricks Runtime to 10.4 LTS ML.

**Comment by aero-girl** [comment] 2023-02-01 15:55
> I have encountered the same issue when using Databricks Runtime 11.3, but successfully installed when I downgraded to the Databricks Runtime to 10.4 LTS ML.

You're right @nakany15 , I downgraded and it worked like a treat! Thank you 👍🏾

**Comment by srowen** [comment] 2023-02-14 21:35
I'm seeing this too. I am wondering about this in the SBT build, which asks for the `assembly` artifact of onnx-protobuf: https://github.com/microsoft/SynapseML/commit/f2e88fdea7c1010118913eecf0457b5daf881d25#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R405 

I'm not sure how this is used later:
https://github.com/microsoft/SynapseML/commit/f2e88fdea7c1010118913eecf0457b5daf881d25#diff-57f58593df9640766bdcfd4510a6ff307ce2056eb6832a52bc8ebc38d8a078e4R25

.... but it seems to not be looking for the assembly artifact there, but the main JAR (?)

**Comment by datashift24** [comment] 2023-02-17 15:54
We had the same issue starting a few weeks ago, downgrading to DBR 10.4 LTS also worked.

**Comment by srowen** [comment] 2023-02-17 16:26
Yeah, I'm not sure why that 'works' other than DBR 10.4 LTS is on Spark 3.2. But the error is about missing `com.microsoft.azure_onnx-protobuf_2.12-0.9.1.jar`, not something particularly to do with Spark. My guess is something in DBR 10.4 also manages to pull in this dependency (?) It may be fine with Spark 3.3, just depends on whether the JARs happen to include this too.

DBR just uses Ivy/SBT for dependency resolution, nothing fancy. This could be down to a change in SBT resolution across versions or something. I was pointing out above that the build seems to depend on the `-assembly` artifact, but then something references the normal non-assembly artifact. Not sure that is a real issue, but it looked like a potential conflict.

**Comment by mhamilton723** [comment] 2023-02-22 12:47
@srowen @aero-girl @nakany15 This is a known issue on Databricks spark 3.3 which we are actively trying to fix (@KeerthiYandaOS leading the charge here). For now the workaround is to use a spark 3.2 cluster. We will report back with a new version to use when we get to the bottom of this. Thanks for your patience

**Comment by KeerthiYandaOS** [comment] 2023-02-23 17:55
@srowen @aero-girl @nakany15 we are seeing this issue because of the [maven resolution](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/11.0#libraries-installed-from-maven-are-now-resolved-in-your-data-plane-by-default) change represented starting from DBR 11.0. can you use `spark.databricks.libraries.enableMavenResolution false` spark configuration on the Spark3.3 cluster to resolve the issue temporarily until our new version of SynapseML is available.

**Comment by srowen** [comment] 2023-02-23 17:56
Ah, I knew it was something like that. SBT vs Maven resolution is an ancient enemy of mine. Thanks for the tip!

**Comment by KeerthiYandaOS** [comment] 2023-03-09 21:07
@srowen @aero-girl @nakany15 Looks like DBR 11.0 doesn't require `spark.databricks.libraries.enableMavenResolution false` anymore, I could install the jar without that property anymore. We also have a new SynapseML version for Spark3.3 which overcomes the need for spark maven resolution property: `com.microsoft.azure:synapseml_2.12:0.11.0-32-6085190e-SNAPSHOT`. Either way, we should be good with Spark3.3 on DBR 11.

Closing this issue as the solution is posted. Please feel free to open it if you are still facing errors. Thank you.

**Comment by aero-girl** [comment] 2023-03-23 13:28
Tested with the following maven coordinates: com.microsoft.azure:synapseml_2.12:0.10.2, and it works! 🙌🏽🚀

**Comment by KeerthiYandaOS** [comment] 2023-03-23 14:41
@aero-girl can you please try installing again with Spark3.3 maven coordinates `com.microsoft.azure:synapseml_2.12:0.11.0-32-6085190e-SNAPSHOT` and see if you still see the error? I was able to install the same version on the `11.3 LTS ML (includes Apache Spark 3.3.0, Scala 2.12)` cluster
![image](https://user-images.githubusercontent.com/98137159/227238274-06b29ae2-f51e-411f-b129-68305c03f773.png)
![image](https://user-images.githubusercontent.com/98137159/227238467-ab4062b9-f942-483f-827f-e59d729092ee.png)

**Comment by KeerthiYandaOS** [comment] 2023-03-23 15:21
@aero-girl can you please provide `https://mmlspark.azureedge.net/maven` as the repository URL as `com.microsoft.azure:synapseml_2.12:0.11.0-32-6085190e-SNAPSHOT` is the SNAPSHOT version and is not published to default maven central repository.
![image](https://user-images.githubusercontent.com/98137159/227250700-24af8bca-721c-4c65-bef8-ceddd5ae576e.png)

**Comment by aero-girl** [comment] 2023-03-23 15:25
> com.microsoft.azure:synapseml_2.12:0.11.0-32-6085190e-SNAPSHOT

@KeerthiYandaOS thank you, that has worked! 🙌🏽😃
![image](https://user-images.githubusercontent.com/5180795/227252101-410624c6-08d2-42d9-b867-379e14690587.png)

**Comment by KeerthiYandaOS** [comment] 2023-03-23 15:27
Thank you for the confirmation @aero-girl. Closing the thread as the issue is resolved.

**Closed** 2023-03-23 15:27 UTC
Labels: bug, databricks
